### ISSUE TITLE
Gives empty .txt files

### ISSUE THREAD

**Issue by ogladkov** [jankolf/GraFIQs#1]
I set the run like that:
`python extract_grafiqs.py
--image-path /home/sm00th/Projects/assets/IMG_3625.jpg
--output-dir /home/sm00th/Projects/apps/GraFIQs/output/
--backbone iresnet100
--weights /home/sm00th/Projects/apps/GraFIQs/backbones/resnet100_ms1mv2_arcface.pth
`

But got empty text files in the output dir...

![2024-05-07_14-40](https://github.com/jankolf/GraFIQs/assets/39189447/f74a21df-fec5-4e0b-a811-76d5819e7805)

**Comment by jankolf** [comment]
Hi Oleg,
could you please try and run the script with the following command:
`python extract_grafiqs.py --image-path /home/sm00th/Projects/assets/ --output-dir /home/sm00th/Projects/apps/GraFIQs/output/ --backbone iresnet100 --weights /home/sm00th/Projects/apps/GraFIQs/backbones/resnet100_ms1mv2_arcface.pth --image-extension jpg`

The script currently does not read a single file, only an entire folder of images that contains images with the extension `--image-extension`.

Best,
Jan

**Comment by ogladkov** [comment]
@jankolf thanks! it works!
But how to interpret the results? I got: 
assets/IMG_0594.jpg 0.022407490760087967
assets/IMG_0631.jpg 0.024729223921895027
assets/IMG_0716.jpg 0.018773064017295837
assets/IMG_0807.jpg 0.03962496668100357
assets/IMG_1478.jpg 0.02287452295422554
assets/IMG_1506.jpg 0.029470067471265793
assets/IMG_1613.jpg 0.020342953503131866
assets/IMG_1780.jpg 0.029832670465111732
assets/IMG_1849.jpg 0.03149200230836868
assets/IMG_1986.jpg 0.022768206894397736
assets/IMG_2023.jpg 0.02831069380044937
assets/IMG_2236.jpg 0.02534307725727558
assets/IMG_2265.jpg 0.020838480442762375
assets/IMG_2477.jpg 0.026965424418449402
assets/IMG_2924.jpg 0.021429385989904404
assets/IMG_7829.jpg 0.02555595338344574
assets/IMG_7830.jpg 0.029234034940600395
assets/IMG_7850.jpg 0.025051038712263107
assets/IMG_7851.jpg 0.020996196195483208
assets/IMG_8684.jpg 0.026479508727788925

**Comment by jankolf** [comment]
The lower the score, the better the image is suited for FR, so the face image was assigned a higher quality.
A higher score indicates that the face image was assigned lower quality and is less suited to perform FR.

**Comment by ogladkov** [comment]
Thank you @jankolf ! Now is clear!
